apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lab
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-lab
  storageClassName: ""

  resources:
    requests:
      storage: 1Gi
