apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: meu-volume

  volumes:
  - name: meu-volume
    persistentVolumeClaim:
      claimName: pvc-lab 
